stages:
  - build
  - test

build:
  stage: build
  script:
    - gradle build -x test
  tags:
    - gradle
  allow_failure: true #Need to figure out how to get gitlab gradle runner to run gradle 5

test:
  stage: test
  script:
    - gradle test
  tags:
    - gradle
  artifacts:
    when: on_failure
    expire_in: 1 day
  allow_failure: true #Need to figure out how to get gitlab gradle runner to run gradle 5
